FROM node:12-alpine AS dist

COPY package*.json ./
COPY . .

RUN npm install --silent

##############################################################

FROM node:12-alpine
WORKDIR /usr/src/app

COPY --from=dist node_modules /usr/src/app/node_modules

RUN apk update && apk add --no-cache tzdata
RUN ln -snf /usr/share/zoneinfo/America/Sao_Paulo \
      /etc/localtime && \
      echo "America/Sao_Paulo" > /etc/timezone

CMD [ "npm", "run", "dev" ]
